[project]
name = "model-webcam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opencv-python-headless>=4.13.0.90",
    "rfdetr>=1.4.0,<2.0",
    "supervision>=0.27.0",
    "transformers<5",
]
